### ISSUE TITLE
Enhancement: Convert from any encoding

### ISSUE THREAD

**Issue by troydemonbreun** [heldinz/gulp-convert-encoding#3]
Using something like jschardet, detect the current encoding and use that as the "from" value instead of UTF8.  This is useful in cases where the encoding is not known until runtime, and it is difficult in gulp to conditionally set the "from" param.

I might be able to assist with a PR.

**Comment by Mucaccino** [comment]
Yes, I felt the same need. We can also use [node-autodetect-decoder-stream](https://github.com/danielgindi/node-autodetect-decoder-stream) to do this.

**Comment by heldinz** [comment]
Hey, this is embarrassingly late but just to wrap this up: I want to keep this plugin as simple as possible and have it do the encoding only. Encoding detection can never be 100% reliable so I'd rather keep that separate.
