### ISSUE TITLE
gulp-util is deprecated

### ISSUE THREAD

**Issue by Bargamut** [heldinz/gulp-convert-encoding#4]
Hi there! )

I've some warning of npm with your package.

Now, I run this:
`npm i gulp-convert-encoding --save-dev`

and see this:
`npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5`

Then I read this [description of deprecation](https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5#635d) gupl-util. Please, read this too.

**Comment by heldinz** [comment]
Just released v2.0 with your changes, thanks!

Closed via 05300e6.
